name: Zaproxy job

# on:
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - 'kubernetes/deployment.yaml'  # Ignore changes to this file to prevent loops
#   pull_request:
#     branches: [ main ]
    
jobs:

 Zap-scan:
     runs-on: ubuntu-latest
     needs: [build]
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Serve build in background
        run: |
          npm install -g serve
          serve -s build -l 3000 &
          sleep 10  # Give server time to start

      - name: Set up Docker login for GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -u root -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable -t http://localhost:3000 -g gen.conf -r zap-report.html

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
         with:
           name: zap-report
           path: zap-report.html
